package ee.jakarta.xml.ns.persistence.orm

import kotlin.String

enum class LockModeType(val value: String) {

	READ("READ"),
	WRITE("WRITE"),
	OPTIMISTIC("OPTIMISTIC"),
	OPTIMISTICFORCEINCREMENT("OPTIMISTIC_FORCE_INCREMENT"),
	PESSIMISTICREAD("PESSIMISTIC_READ"),
	PESSIMISTICWRITE("PESSIMISTIC_WRITE"),
	PESSIMISTICFORCEINCREMENT("PESSIMISTIC_FORCE_INCREMENT"),
	NONE("NONE"),
}
